---
title: "R Notebook"
output: html_notebook
---
```{r setup and require library, include=FALSE, WARNING = FALSE}
library(dplyr) #for mutate factor level of brand
library(data.table) #for set DT checking brand
library(ggplot2)
```

```{r read data, include=FALSE}
df_hh <- read.csv("../../../../data/df_hhcoice_4cate2format.csv")
```

```{r create store information}

df_store <- read.csv("../../../../data/df_scanner_discount_threshold_filteredSKU.csv")
#Price of brand b in period t, computed as a sales-weighted average across its SKUs sold in period t
df_store$pricebeforeperunit <- df_store$spendingbeforedisc/df_store$sales_volume
df_store$finalpriceperunit <- df_store$finalspending/df_store$sales_volume
df_store$discountperunit <- df_store$totaldiscount/df_store$sales_volume
#calculated weight
weeklysalesbySKU<-setDT(df_store)[, .(totalsales_SKU=sum(sales_volume),pricebeforeperunit=mean(pricebeforeperunit),finalpriceperunit=mean(finalpriceperunit),discountperunit=mean(discountperunit)), .(produkt_id,vecka,brand_PLNB,category,format)] 
weeklysalesbybrand<-setDT(df_store)[, .(totalsales_brand=sum(sales_volume)), .(vecka,brand_PLNB,category,format)] 

df_weightcalc_SKUbrand<- merge(weeklysalesbySKU,weeklysalesbybrand, by=c("vecka","brand_PLNB","category","format"))
df_weightcalc_SKUbrand$wp <- df_weightcalc_SKUbrand$totalsales_SKU/df_weightcalc_SKUbrand$totalsales_brand
#check<-setDT(df_weightcalc_SKUbrand)[, .(totalwp=sum(wp)), .(vecka,brand_PLNB)] #check if weight sum to 1

df_weightcalc_SKUbrand$avgpricebefore <- df_weightcalc_SKUbrand$pricebeforeperunit*df_weightcalc_SKUbrand$wp
df_weightcalc_SKUbrand$avgfinalprice <- df_weightcalc_SKUbrand$finalpriceperunit*df_weightcalc_SKUbrand$wp
df_weightcalc_SKUbrand$avgdiscount <- df_weightcalc_SKUbrand$discountperunit*df_weightcalc_SKUbrand$wp
df_bybrand <- setDT(df_weightcalc_SKUbrand)[, .(totalvolume=sum(totalsales_SKU),LL=uniqueN(produkt_id),avgpricebefore=sum(avgpricebefore),avgfinalprice=sum(avgfinalprice),avgdiscount=sum(avgdiscount)), .(vecka,brand_PLNB,category,format)]

weeklysalesbybrand_PL <- df_bybrand[df_bybrand$brand_PLNB == "PL",]
weeklysalesbybrand_NB <- df_bybrand[df_bybrand$brand_PLNB == "NB",]

#set NB and PL price
colnames(weeklysalesbybrand_NB)[colnames(weeklysalesbybrand_NB) == "avgfinalprice"] ="avgfinalprice_NB"
colnames(weeklysalesbybrand_NB)[colnames(weeklysalesbybrand_NB) == "avgpricebefore"] ="avgpricebefore_NB"
colnames(weeklysalesbybrand_NB)[colnames(weeklysalesbybrand_NB) == "avgdiscount"] ="avgdiscount_NB"
colnames(weeklysalesbybrand_PL)[colnames(weeklysalesbybrand_PL) == "avgfinalprice"] ="avgfinalprice_PL"
colnames(weeklysalesbybrand_PL)[colnames(weeklysalesbybrand_PL) == "avgpricebefore"] ="avgpricebefore_PL"
colnames(weeklysalesbybrand_PL)[colnames(weeklysalesbybrand_PL) == "avgdiscount"] ="avgdiscount_PL"



df_storeinfo<- merge(weeklysalesbybrand_PL,weeklysalesbybrand_NB, by=c("vecka","format","category"))

relevant_storedf <- df_storeinfo[,c("vecka","avgpricebefore_NB","avgdiscount_NB","avgpricebefore_PL","avgdiscount_PL","category","format")]

remove(list=c("df_store", "weeklysalesbySKU","weeklysalesbybrand","weeklysalesbybrand_NB","weeklysalesbybrand_PL","df_weightcalc_SKUbrand","df_bybrand","df_storeinfo")) 
```

```{r}
df_choice <- merge(df_hh,relevant_storedf, by=c("vecka","category","format"))
remove(list=c("df_hh", "relevant_storedf"))
```

```{r}
#Construct relevant variable
df_data <- df_choice[df_choice$category == "Cereals",]
#df_data <- df_data[!duplicated(df_data, by = c("vecka","hushall_id"))]
df_data  <- unique(df_data,  by = c("vecka", "hushall_id")) #drop the chance that they go shopping that week
setDT(df_data)
df_data$choice_PL <- ifelse(df_data$brand_PLNB == "PL", 1, 0)
df_data$choice_NB <- ifelse(df_data$brand_PLNB == "NB", 1, 0)


lag_1 <- function(x, k = 1) head(c(rep(NA, k), x), length(x))

#IRP variable
df_data<-df_data[order(df_data$hushall_id,df_data$vecka),]
lamda_IR = 0.90
df_data$avgpricebefore1_PL <- ave(df_data$avgpricebefore_PL, df_data$hushall_id, FUN= lag_1)
df_data$avgpricebefore2_PL <- ave(df_data$avgpricebefore1_PL, df_data$hushall_id, FUN= lag_1)
df_data$IR_avgpricebefore1_PL <- lamda_IR*df_data$avgpricebefore2_PL + (1-lamda_IR)*df_data$avgpricebefore1_PL
df_data$IR_avgpricebefore_PL <- lamda_IR*df_data$IR_avgpricebefore1_PL + (1-lamda_IR)*df_data$avgpricebefore1_PL
df_data$avgdiscount1_PL <- ave(df_data$avgdiscount_PL, df_data$hushall_id, FUN= lag_1)
df_data$avgdiscount2_PL <- ave(df_data$avgdiscount1_PL, df_data$hushall_id, FUN= lag_1)
df_data$IR_avgdiscount1_PL <- lamda_IR*df_data$avgdiscount2_PL + (1-lamda_IR)*df_data$avgdiscount1_PL
df_data$IR_avgdiscount_PL <- lamda_IR*df_data$IR_avgdiscount1_PL + (1-lamda_IR)*df_data$avgdiscount1_PL
df_data$avgpricebefore1_NB <- ave(df_data$avgpricebefore_NB, df_data$hushall_id, FUN= lag_1)
df_data$avgpricebefore2_NB <- ave(df_data$avgpricebefore1_NB, df_data$hushall_id, FUN= lag_1)
df_data$IR_avgpricebefore1_NB <- lamda_IR*df_data$avgpricebefore2_NB + (1-lamda_IR)*df_data$avgpricebefore1_NB
df_data$IR_avgpricebefore_NB <- lamda_IR*df_data$IR_avgpricebefore1_NB + (1-lamda_IR)*df_data$avgpricebefore1_NB
df_data$avgdiscount1_NB <- ave(df_data$avgdiscount_NB, df_data$hushall_id, FUN= lag_1)
df_data$avgdiscount2_NB <- ave(df_data$avgdiscount1_NB, df_data$hushall_id, FUN= lag_1)
df_data$IR_avgdiscount1_NB <- lamda_IR*df_data$avgdiscount2_NB + (1-lamda_IR)*df_data$avgdiscount1_NB
df_data$IR_avgdiscount_NB <- lamda_IR*df_data$IR_avgdiscount1_NB + (1-lamda_IR)*df_data$avgdiscount1_NB

#creategain_loss
df_data<-df_data[order(df_data$hushall_id,df_data$vecka),]
df_data$pricegap_PL <- df_data$avgpricebefore_PL- df_data$IR_avgpricebefore_PL
df_data$discountgap_PL <- df_data$avgdiscount_PL- df_data$IR_avgdiscount_PL
df_data$pricegap_NB <- df_data$avgpricebefore_NB- df_data$IR_avgpricebefore_NB
df_data$discountgap_NB <- df_data$avgdiscount_NB- df_data$IR_avgdiscount_NB

df_data$pricegaploss_PL <- ifelse(df_data$pricegap_PL >0, df_data$pricegap_PL, 0)
df_data$pricegapgain_PL <- ifelse(df_data$pricegap_PL <0, -df_data$pricegap_PL, 0)
df_data$discountgaploss_PL <- ifelse(df_data$discountgap_PL <0, -df_data$discountgap_PL, 0)
df_data$discountgapgain_PL <- ifelse(df_data$discountgap_PL >0, df_data$discountgap_PL, 0)
df_data$pricegaploss_NB <- ifelse(df_data$pricegap_NB >0, df_data$pricegap_NB, 0)
df_data$pricegapgain_NB <- ifelse(df_data$pricegap_NB <0, -df_data$pricegap_NB, 0)
df_data$discountgaploss_NB <- ifelse(df_data$discountgap_NB <0, -df_data$discountgap_NB, 0)
df_data$discountgapgain_NB <- ifelse(df_data$discountgap_NB >0, df_data$discountgap_NB, 0)

#create seperate variable for hypermarket and supermarket
df_data$hyperpricegain_PL <- ifelse(df_data$pricegapgain_PL >0 & df_data$format == "hypermarket" , df_data$pricegapgain_PL, 0)
df_data$hyperpriceloss_PL <- ifelse(df_data$pricegaploss_PL >0 & df_data$format == "hypermarket" , df_data$pricegaploss_PL, 0)
df_data$hyperdiscountgain_PL <- ifelse(df_data$discountgapgain_PL >0 & df_data$format == "hypermarket" , df_data$discountgapgain_PL, 0)
df_data$hyperdiscountloss_PL <- ifelse(df_data$discountgaploss_PL >0 & df_data$format == "hypermarket" , df_data$discountgaploss_PL, 0)
df_data$superpricegain_PL <- ifelse(df_data$pricegapgain_PL >0 & df_data$format == "supermarket" , df_data$pricegapgain_PL, 0)
df_data$superpriceloss_PL <- ifelse(df_data$pricegaploss_PL >0 & df_data$format == "supermarket" , df_data$pricegaploss_PL, 0)
df_data$superdiscountgain_PL <- ifelse(df_data$discountgapgain_PL >0 & df_data$format == "supermarket" , df_data$discountgapgain_PL, 0)
df_data$superdiscountloss_PL <- ifelse(df_data$discountgaploss_PL >0 & df_data$format == "supermarket" , df_data$discountgaploss_PL, 0)
df_data$hyperpricegain_NB <- ifelse(df_data$pricegapgain_NB >0 & df_data$format == "hypermarket" , df_data$pricegapgain_NB, 0)
df_data$hyperpriceloss_NB <- ifelse(df_data$pricegaploss_NB >0 & df_data$format == "hypermarket" , df_data$pricegaploss_NB, 0)
df_data$hyperdiscountgain_NB <- ifelse(df_data$discountgapgain_NB >0 & df_data$format == "hypermarket" , df_data$discountgapgain_NB, 0)
df_data$hyperdiscountloss_NB <- ifelse(df_data$discountgaploss_NB >0 & df_data$format == "hypermarket" , df_data$discountgaploss_NB, 0)
df_data$superpricegain_NB <- ifelse(df_data$pricegapgain_NB >0 & df_data$format == "supermarket" , df_data$pricegapgain_NB, 0)
df_data$superpriceloss_NB <- ifelse(df_data$pricegaploss_NB >0 & df_data$format == "supermarket" , df_data$pricegaploss_NB, 0)
df_data$superdiscountgain_NB <- ifelse(df_data$discountgapgain_NB >0 & df_data$format == "supermarket" , df_data$discountgapgain_NB, 0)
df_data$superdiscountloss_NB <- ifelse(df_data$discountgaploss_NB >0 & df_data$format == "supermarket" , df_data$discountgaploss_NB, 0)

#loyalty variable
df_data<-df_data[order(df_data$hushall_id,df_data$vecka),]
alpha_loyal = 0.89
df_data$loyal1_PL <- ave(df_data$choice_PL, df_data$hushall_id, FUN= lag_1)
df_data$loyal_PL <- alpha_loyal*df_data$loyal1_PL + (1-alpha_loyal)*df_data$choice_PL
df_data$loyal1_NB <- ave(df_data$choice_NB, df_data$hushall_id, FUN= lag_1)
df_data$loyal_NB <- alpha_loyal*df_data$loyal1_NB + (1-alpha_loyal)*df_data$choice_NB
df_data$loyal <- ifelse(df_data$brand_PLNB == "NB", df_data$loyal_NB, df_data$loyal_PL)



#format share
df_data$supermarket_shop <- ifelse(df_data$format == "supermarket", 1, 0)
df_data$shoppingtime <- 1

df_data<-df_data[order(df_data$hushall_id,df_data$vecka),]
df_data$hushall_id <- as.factor(df_data$hushall_id)

df_data[, TotalShoppingttime := cumsum(shift(shoppingtime, fill = 1)), by = hushall_id]
df_data[, Supermarkettime := cumsum(shift(supermarket_shop, fill = 0)), by = hushall_id]
df_data$sup_share <- df_data$Supermarkettime/df_data$TotalShoppingttime

df_data <- na.omit(df_data) #We drop first week

df_data <- df_data[!duplicated(df_data, by = c("vecka","hushall_id"))]

#df_data <- [,c("vecka","hushall_id","discountgaploss_PL","avgpricebefore_PL","avgdiscount_PL","category","format")]
```


```{r}
library("mlogit")
data("Train", package = "mlogit")
Train$choiceid <- 1:nrow(Train)
Tr <- dfidx(Train, choice = "choice", varying = 4:11, sep = "_",
            opposite = c("price", "comfort", "time", "change"),
            idx = list(c("choiceid", "id")), idnames = c("chid", "alt"))

dt_unique$vecka <- as.factor(dt_unique$vecka)
dt_unique$hushall_id <- as.factor(dt_unique$hushall_id)
dt_unique$choice_id <- seq(1:132343)

Tr.choice <- dfidx(dt_unique, choice = "choice",
            idx = list(c("choice_id", "hushall_id")))





df_data$choiceid <- 1:nrow(df_data)
df_choice_tranformed <- dfidx(df_data, choice = "brand_PLNB", varying = 42:61, sep = "_",
            opposite = c("hyperpricegain", "hyperpriceloss", "hyperdiscountgain", "hyperdiscountloss",
                         "superpricegain", "superpriceloss", "superdiscountgain", "superdiscountloss",
                         "loyal1","loyal"),
                   idx = list(c("choiceid", "hushall_id")), idnames = c("chid", "id" ,"brand"))


choice_ml <- mlogit(choice ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + supshare| - 1, df_choice_tranformed)



df_choice_tranformed_3 <- dfidx(df_data, choice = "brand_PLNB", varying = 42:61, sep = "_",
            opposite = c("hyperpricegain", "hyperpriceloss", "hyperdiscountgain", "hyperdiscountloss",
                         "superpricegain", "superpriceloss", "superdiscountgain", "superdiscountloss"
                         ))


df_choice_tranformed_3$choice <- as.numeric(df_choice_tranformed_3$brand_PLNB)
#

df_choicevariant <- df_choice_tranformed_3[,c("vecka","hushall_id","choice",
                                              "hyperpriceloss","hyperdiscountgain","hyperdiscountloss",
               "superpricegain","superpriceloss","superdiscountgain","superdiscountloss")]
extract_index <- data.frame(df_choicevariant[,11])
setnames(extract_index, new = c("choice_id","brand"))
df_choicevariant <- cbind(df_choicevariant,extract_index)



df_choiceinvariant <- data.frame(df_data[,c("vecka","hushall_id","brand_PLNB",
                                              "loyal_PL","loyal_NB","sup_share")])

df_test <- merge(df_choicevariant,df_choiceinvariant, by=c("vecka","hushall_id"))
df_test$NB_intercept <- ifelse(df_test$brand_PLNB == "NB", 1, 0)
df_test$NB_intercept <- ifelse(df_test[,11] == "NB", 1, 0)


setnames(df_choice1, c(8,9), c("choice_id","brand"))
colnames(df_choice1)[,(12:13)] <- c("choice_id","brand")


library(logitr)
mxl_pref <- logitr(
  data     = df_choice_tranformed_3,
  outcome  = 'choice',
  obsID    = 'choiceid',
  panelID  = 'hushall_id',
  pars     = c('hyperpricegain','hyperpriceloss','hyperdiscountgain', 'hyperdiscountloss', 
              'superpricegain', 'superpriceloss', 'superdiscountgain', 'superdiscountloss',
              'sup_share'),
  randPars = c(hyperpricegain = "n", hyperpriceloss = "n", hyperdiscountgain = "n", hyperdiscountloss = "n",
                                superpricegain = "n", superpriceloss = "n", superdiscountgain = "n", superdiscountloss= "n"),
  numMultiStarts = 10
)

library(logitr)
mxl_pref <- logitr(
  data     = df_choice_tranformed_3,
  outcome  = 'choice',
  obsID    = 'choiceid',
  panelID  = 'hushall_id',
  pars     = c('hyperpricegain','hyperpriceloss','hyperdiscountgain', 'hyperdiscountloss', 
              'superpricegain', 'superpriceloss', 'superdiscountgain', 'superdiscountloss',
              'sup_share')
)


library(lme4)

m <- glmer(choice ~ 0 + hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + loyal + sup_share + NB_intercept + (1 | hushall_id), data = df_choice_tranformed_3, family = binomial, control = glmerControl(optimizer = "bobyqa"),nAGQ = 10)
```

```{r}
library(brms)
# Define the choice model formula
formula <- bf(choice ~ hyper_pricegain + hyper_priceloss + hyper_discountgain + hyper_discountloss 
                       + super_pricegain + super_priceloss + super_discountgain + super_discountloss
                       + PL_loyal + sup_share + (1|hushall_id))

# Specify priors and other options (adjust as needed)
prior <- prior(normal(0, 1), class = "b")
options <- list(iter = 2000, warmup = 1000, chains = 4)

# Fit the choice model
model <- brm(formula, data = dt_unique, prior = prior, 
             iter = 2000, warmup = 1000, chains = 4)

# Summarize the model
summary(model)

```
```{r}
library(logitr)

mxl_pref <- logitr(
  data     = dt_unique,
  outcome  = 'choice',
  obsID    = 'choice_id',
  panelID  = 'hushall_id',
  pars     = c('hyper_pricegain','hyper_priceloss','hyper_discountgain', 'hyper_discountloss', 
              'super_pricegain', 'super_priceloss', 'super_discountgain', 'super_discountloss',
              'PL_loyal','sup_share'),
  randPars = c(hyper_pricegain = "n", hyper_priceloss = "n", hyper_discountgain = "n", hyper_discountloss = "n",
                                super_pricegain = "n", super_priceloss = "n", super_discountgain = "n", super_discountloss= "n"),
  numMultiStarts = 10
)

hyper_pricegain + hyper_priceloss + hyper_discountgain + hyper_discountloss 
                       + super_pricegain + super_priceloss + super_discountgain + super_discountloss
                       + PL_loyal + sup_share
```


