---
title: "R Notebook"
output: html_notebook
---
```{r setup and require library, include=FALSE, WARNING = FALSE}
library(dplyr) #for mutate factor level of brand
library(data.table) #for set DT checking brand
library(ggplot2)
```

```{r read data, include=FALSE}
df_hh <- read.csv("../../../../data/df_hhcoice_4cate2format.csv")
```

```{r create store information}

df_store <- read.csv("../../../../data/df_scanner_discount_threshold_filteredSKU.csv")
#Price of brand b in period t, computed as a sales-weighted average across its SKUs sold in period t
df_store$pricebeforeperunit <- df_store$spendingbeforedisc/df_store$sales_volume
df_store$finalpriceperunit <- df_store$finalspending/df_store$sales_volume
df_store$discountperunit <- df_store$totaldiscount/df_store$sales_volume
#calculated weight
weeklysalesbySKU<-setDT(df_store)[, .(totalsales_SKU=sum(sales_volume),pricebeforeperunit=mean(pricebeforeperunit),finalpriceperunit=mean(finalpriceperunit),discountperunit=mean(discountperunit)), .(produkt_id,vecka,brand_PLNB,category,format)] 
weeklysalesbybrand<-setDT(df_store)[, .(totalsales_brand=sum(sales_volume)), .(vecka,brand_PLNB,category,format)] 

df_weightcalc_SKUbrand<- merge(weeklysalesbySKU,weeklysalesbybrand, by=c("vecka","brand_PLNB","category","format"))
df_weightcalc_SKUbrand$wp <- df_weightcalc_SKUbrand$totalsales_SKU/df_weightcalc_SKUbrand$totalsales_brand
#check<-setDT(df_weightcalc_SKUbrand)[, .(totalwp=sum(wp)), .(vecka,brand_PLNB)] #check if weight sum to 1

df_weightcalc_SKUbrand$avgpricebefore <- df_weightcalc_SKUbrand$pricebeforeperunit*df_weightcalc_SKUbrand$wp
df_weightcalc_SKUbrand$avgfinalprice <- df_weightcalc_SKUbrand$finalpriceperunit*df_weightcalc_SKUbrand$wp
df_weightcalc_SKUbrand$avgdiscount <- df_weightcalc_SKUbrand$discountperunit*df_weightcalc_SKUbrand$wp
df_bybrand <- setDT(df_weightcalc_SKUbrand)[, .(totalvolume=sum(totalsales_SKU),LL=uniqueN(produkt_id),avgpricebefore=sum(avgpricebefore),avgfinalprice=sum(avgfinalprice),avgdiscount=sum(avgdiscount)), .(vecka,brand_PLNB,category,format)]

weeklysalesbybrand_PL <- df_bybrand[df_bybrand$brand_PLNB == "PL",]
weeklysalesbybrand_NB <- df_bybrand[df_bybrand$brand_PLNB == "NB",]

#set NB and PL price
colnames(weeklysalesbybrand_NB)[colnames(weeklysalesbybrand_NB) == "avgfinalprice"] ="avgfinalprice_NB"
colnames(weeklysalesbybrand_NB)[colnames(weeklysalesbybrand_NB) == "avgpricebefore"] ="avgpricebefore_NB"
colnames(weeklysalesbybrand_NB)[colnames(weeklysalesbybrand_NB) == "avgdiscount"] ="avgdiscount_NB"
colnames(weeklysalesbybrand_PL)[colnames(weeklysalesbybrand_PL) == "avgfinalprice"] ="avgfinalprice_PL"
colnames(weeklysalesbybrand_PL)[colnames(weeklysalesbybrand_PL) == "avgpricebefore"] ="avgpricebefore_PL"
colnames(weeklysalesbybrand_PL)[colnames(weeklysalesbybrand_PL) == "avgdiscount"] ="avgdiscount_PL"



df_storeinfo<- merge(weeklysalesbybrand_PL,weeklysalesbybrand_NB, by=c("vecka","format","category"))

agg_relevant_storedf <- df_storeinfo[,c("vecka","avgpricebefore_NB","avgdiscount_NB","avgpricebefore_PL","avgdiscount_PL","category","format")]

storedf_format_hyper <- agg_relevant_storedf[agg_relevant_storedf$format == "hypermarket",]
storedf_format_hyper$hyperprice_PL <- storedf_format_hyper$avgpricebefore_PL
storedf_format_hyper$hyperdiscount_PL <- storedf_format_hyper$avgdiscount_PL
storedf_format_hyper$hyperprice_NB <- storedf_format_hyper$avgpricebefore_NB
storedf_format_hyper$hyperdiscount_NB <- storedf_format_hyper$avgdiscount_NB
relevant_storedf_hyper <- storedf_format_hyper[,c("vecka","category","hyperprice_PL","hyperdiscount_PL","hyperprice_NB","hyperdiscount_NB")]
storedf_format_super <- agg_relevant_storedf[agg_relevant_storedf$format == "supermarket",]
storedf_format_super$superprice_PL <- storedf_format_super$avgpricebefore_PL
storedf_format_super$superdiscount_PL <- storedf_format_super$avgdiscount_PL
storedf_format_super$superprice_NB <- storedf_format_super$avgpricebefore_NB
storedf_format_super$superdiscount_NB <- storedf_format_super$avgdiscount_NB
relevant_storedf_super <- storedf_format_super[,c("vecka","category","superprice_PL","superdiscount_PL","superprice_NB","superdiscount_NB")]

relevant_storedf_0 <- merge(agg_relevant_storedf,relevant_storedf_hyper, by=c("vecka","category"),all.x = TRUE)
relevant_storedf <- merge(relevant_storedf_0,relevant_storedf_super, by=c("vecka","category"),all.x = TRUE)




remove(list=c("df_store", "weeklysalesbySKU","weeklysalesbybrand","weeklysalesbybrand_NB","weeklysalesbybrand_PL","df_weightcalc_SKUbrand","df_bybrand","df_storeinfo")) 
```

```{r}
df_choice <- merge(df_hh,relevant_storedf, by=c("vecka","category","format"))
remove(list=c("df_hh", "relevant_storedf"))
```

```{r}
#Construct relevant variable
df_data <- df_choice[df_choice$category == "Cereals",]
#df_data <- df_data[!duplicated(df_data, by = c("vecka","hushall_id"))]
df_data  <- unique(df_data,  by = c("vecka", "hushall_id")) #drop the chance that they go shopping that week
setDT(df_data)
df_data$choice_PL <- ifelse(df_data$brand_PLNB == "PL", 1, 0)
df_data$choice_NB <- ifelse(df_data$brand_PLNB == "NB", 1, 0)


lag_1 <- function(x, k = 1) head(c(rep(NA, k), x), length(x))

#IRP variable
df_data<-df_data[order(df_data$hushall_id,df_data$vecka),]
lamda_IR = 0.90
df_data$avgpricebefore1_PL <- ave(df_data$avgpricebefore_PL, df_data$hushall_id, FUN= lag_1)
df_data$avgpricebefore2_PL <- ave(df_data$avgpricebefore1_PL, df_data$hushall_id, FUN= lag_1)
df_data$IR_avgpricebefore1_PL <- lamda_IR*df_data$avgpricebefore2_PL + (1-lamda_IR)*df_data$avgpricebefore1_PL
df_data$IR_avgpricebefore_PL <- lamda_IR*df_data$IR_avgpricebefore1_PL + (1-lamda_IR)*df_data$avgpricebefore1_PL
df_data$avgdiscount1_PL <- ave(df_data$avgdiscount_PL, df_data$hushall_id, FUN= lag_1)
df_data$avgdiscount2_PL <- ave(df_data$avgdiscount1_PL, df_data$hushall_id, FUN= lag_1)
df_data$IR_avgdiscount1_PL <- lamda_IR*df_data$avgdiscount2_PL + (1-lamda_IR)*df_data$avgdiscount1_PL
df_data$IR_avgdiscount_PL <- lamda_IR*df_data$IR_avgdiscount1_PL + (1-lamda_IR)*df_data$avgdiscount1_PL
df_data$avgpricebefore1_NB <- ave(df_data$avgpricebefore_NB, df_data$hushall_id, FUN= lag_1)
df_data$avgpricebefore2_NB <- ave(df_data$avgpricebefore1_NB, df_data$hushall_id, FUN= lag_1)
df_data$IR_avgpricebefore1_NB <- lamda_IR*df_data$avgpricebefore2_NB + (1-lamda_IR)*df_data$avgpricebefore1_NB
df_data$IR_avgpricebefore_NB <- lamda_IR*df_data$IR_avgpricebefore1_NB + (1-lamda_IR)*df_data$avgpricebefore1_NB
df_data$avgdiscount1_NB <- ave(df_data$avgdiscount_NB, df_data$hushall_id, FUN= lag_1)
df_data$avgdiscount2_NB <- ave(df_data$avgdiscount1_NB, df_data$hushall_id, FUN= lag_1)
df_data$IR_avgdiscount1_NB <- lamda_IR*df_data$avgdiscount2_NB + (1-lamda_IR)*df_data$avgdiscount1_NB
df_data$IR_avgdiscount_NB <- lamda_IR*df_data$IR_avgdiscount1_NB + (1-lamda_IR)*df_data$avgdiscount1_NB

#creategain_loss
df_data<-df_data[order(df_data$hushall_id,df_data$vecka),]
df_data$pricegap_PL <- df_data$avgpricebefore_PL- df_data$IR_avgpricebefore_PL
df_data$discountgap_PL <- df_data$avgdiscount_PL- df_data$IR_avgdiscount_PL
df_data$pricegap_NB <- df_data$avgpricebefore_NB- df_data$IR_avgpricebefore_NB
df_data$discountgap_NB <- df_data$avgdiscount_NB- df_data$IR_avgdiscount_NB

df_data$pricegaploss_PL <- ifelse(df_data$pricegap_PL >0, df_data$pricegap_PL, 0)
df_data$pricegapgain_PL <- ifelse(df_data$pricegap_PL <0, -df_data$pricegap_PL, 0)
df_data$discountgaploss_PL <- ifelse(df_data$discountgap_PL <0, -df_data$discountgap_PL, 0)
df_data$discountgapgain_PL <- ifelse(df_data$discountgap_PL >0, df_data$discountgap_PL, 0)
df_data$pricegaploss_NB <- ifelse(df_data$pricegap_NB >0, df_data$pricegap_NB, 0)
df_data$pricegapgain_NB <- ifelse(df_data$pricegap_NB <0, -df_data$pricegap_NB, 0)
df_data$discountgaploss_NB <- ifelse(df_data$discountgap_NB <0, -df_data$discountgap_NB, 0)
df_data$discountgapgain_NB <- ifelse(df_data$discountgap_NB >0, df_data$discountgap_NB, 0)

#create seperate variable for hypermarket and supermarket
df_data$hyperpricegain_PL <- ifelse(df_data$pricegapgain_PL >0 & df_data$format == "hypermarket" , df_data$pricegapgain_PL, 0)
df_data$hyperpriceloss_PL <- ifelse(df_data$pricegaploss_PL >0 & df_data$format == "hypermarket" , df_data$pricegaploss_PL, 0)
df_data$hyperdiscountgain_PL <- ifelse(df_data$discountgapgain_PL >0 & df_data$format == "hypermarket" , df_data$discountgapgain_PL, 0)
df_data$hyperdiscountloss_PL <- ifelse(df_data$discountgaploss_PL >0 & df_data$format == "hypermarket" , df_data$discountgaploss_PL, 0)
df_data$superpricegain_PL <- ifelse(df_data$pricegapgain_PL >0 & df_data$format == "supermarket" , df_data$pricegapgain_PL, 0)
df_data$superpriceloss_PL <- ifelse(df_data$pricegaploss_PL >0 & df_data$format == "supermarket" , df_data$pricegaploss_PL, 0)
df_data$superdiscountgain_PL <- ifelse(df_data$discountgapgain_PL >0 & df_data$format == "supermarket" , df_data$discountgapgain_PL, 0)
df_data$superdiscountloss_PL <- ifelse(df_data$discountgaploss_PL >0 & df_data$format == "supermarket" , df_data$discountgaploss_PL, 0)
df_data$hyperpricegain_NB <- ifelse(df_data$pricegapgain_NB >0 & df_data$format == "hypermarket" , df_data$pricegapgain_NB, 0)
df_data$hyperpriceloss_NB <- ifelse(df_data$pricegaploss_NB >0 & df_data$format == "hypermarket" , df_data$pricegaploss_NB, 0)
df_data$hyperdiscountgain_NB <- ifelse(df_data$discountgapgain_NB >0 & df_data$format == "hypermarket" , df_data$discountgapgain_NB, 0)
df_data$hyperdiscountloss_NB <- ifelse(df_data$discountgaploss_NB >0 & df_data$format == "hypermarket" , df_data$discountgaploss_NB, 0)
df_data$superpricegain_NB <- ifelse(df_data$pricegapgain_NB >0 & df_data$format == "supermarket" , df_data$pricegapgain_NB, 0)
df_data$superpriceloss_NB <- ifelse(df_data$pricegaploss_NB >0 & df_data$format == "supermarket" , df_data$pricegaploss_NB, 0)
df_data$superdiscountgain_NB <- ifelse(df_data$discountgapgain_NB >0 & df_data$format == "supermarket" , df_data$discountgapgain_NB, 0)
df_data$superdiscountloss_NB <- ifelse(df_data$discountgaploss_NB >0 & df_data$format == "supermarket" , df_data$discountgaploss_NB, 0)

#loyalty variable
df_data<-df_data[order(df_data$hushall_id,df_data$vecka),]
alpha_loyal = 0.89
df_data$loyal1_PL <- ave(df_data$choice_PL, df_data$hushall_id, FUN= lag_1)
df_data$loyal_PL <- alpha_loyal*df_data$loyal1_PL + (1-alpha_loyal)*df_data$choice_PL
df_data$loyal1_NB <- ave(df_data$choice_NB, df_data$hushall_id, FUN= lag_1)
df_data$loyal_NB <- alpha_loyal*df_data$loyal1_NB + (1-alpha_loyal)*df_data$choice_NB
df_data$loyal <- ifelse(df_data$brand_PLNB == "NB", df_data$loyal_NB, df_data$loyal_PL)



#format share
df_data$supermarket_shop <- ifelse(df_data$format == "supermarket", 1, 0)
df_data$shoppingtime <- 1
df_data$hypermarket_shop <- ifelse(df_data$format == "hypermarket", 1, 0)

df_data<-df_data[order(df_data$hushall_id,df_data$vecka),]
df_data$hushall_id <- as.factor(df_data$hushall_id)

df_data[, TotalShoppingttime := cumsum(shift(shoppingtime, fill = 1)), by = hushall_id]
df_data[, supermarkettime := cumsum(shift(supermarket_shop, fill = 0)), by = hushall_id]
df_data[, hypermarkettime := cumsum(shift(hypermarket_shop, fill = 0)), by = hushall_id]
df_data$sup_share <- df_data$supermarkettime/df_data$TotalShoppingttime
df_data$hyper_share <- df_data$hypermarkettime/df_data$TotalShoppingttime

df_data <- na.omit(df_data) #We drop first week

df_data <- df_data[!duplicated(df_data, by = c("vecka","hushall_id"))]

#df_data <- [,c("vecka","hushall_id","discountgaploss_PL","avgpricebefore_PL","avgdiscount_PL","category","format")]
#remove(list=c("df_choice"))
```

```{r drop 1 observation}
hh_choice_count<-setDT(df_data)[, .N, .(hushall_id)]
hh_choice_complete<-subset(hh_choice_count, N >= 2)

hh_choice_complete$hushall_id <- as.factor(hh_choice_complete$hushall_id)
hh_choice_complete <- hh_choice_complete%>% mutate(hushall_id=droplevels(hushall_id))

df_data_complete <- df_data[df_data$hushall_id %in% hh_choice_complete$hushall_id, ]
    
df_data_complete <- df_data_complete %>% mutate(hushall_id=droplevels(hushall_id))
```



```{r}
library("mlogit")

df_choice_rearranged <-df_data_complete[,c("vecka","hushall_id","brand_PLNB",
                                  "hyperprice_PL","hyperprice_NB","hyperdiscount_PL","hyperdiscount_NB",
                                  "superprice_PL","superprice_NB","superdiscount_PL","superdiscount_NB",
                                  "hyperpricegain_PL","hyperpricegain_NB","hyperpriceloss_PL","hyperpriceloss_NB",
                                  "hyperdiscountgain_PL","hyperdiscountgain_NB","hyperdiscountloss_PL","hyperdiscountloss_NB",
                                  "superpricegain_PL","superpricegain_NB","superpriceloss_PL","superpriceloss_NB",
                                  "superdiscountgain_PL","superdiscountgain_NB","superdiscountloss_PL","superdiscountloss_NB")]

df_choice_tranformed <- dfidx(df_choice_rearranged, choice = "brand_PLNB", varying = 4:27, sep = "_")
df_choice_tranformed$choice <- as.numeric(df_choice_tranformed$brand_PLNB)


df_choicevariant_0 <- data.frame(df_choice_tranformed[,c("vecka","hushall_id","choice",                                                                              "hyperprice","hyperdiscount","superprice","superdiscount",          
                              "hyperpricegain","hyperpriceloss","hyperdiscountgain","hyperdiscountloss",
               "superpricegain","superpriceloss","superdiscountgain","superdiscountloss")])
extract_index <- data.frame(df_choicevariant_0[,16])
setnames(extract_index, new = c("chid","brand_alt"))
df_choicevariant<- cbind(df_choicevariant_0,extract_index)



df_choiceinvariant <- data.frame(df_data[,c("vecka","hushall_id","brand_PLNB",
                                              "loyal_PL","loyal_NB","sup_share","hyper_share")])

df <- merge(df_choicevariant,df_choiceinvariant, by=c("vecka","hushall_id"))


df$NB_intercept <- ifelse(df$brand_alt == "NB", 1, 0)
df$PL_intercept <- ifelse(df$brand_alt == "PL", 1, 0)
df$loyal <- ifelse(df$brand_alt == "NB", df$loyal_NB, df$loyal_PL)

remove(list=c("df_choice_tranformed","df_choicevariant_0","df_choicevariant","df_choiceinvariant"))


library(lme4)
m_1 <- glmer(choice ~ 0 + hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + sup_share + NB_intercept + loyal  + (1 | hushall_id), data = df, family = binomial, control = glmerControl(optimizer = "bobyqa"),nAGQ = 10)

m_nolevel <- glmer(choice ~ 0 + hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + NB_intercept + loyal  + (1 | hushall_id), data = df, family = binomial, control = glmerControl(optimizer = "bobyqa"),nAGQ = 10)
```
```{r}
choice_R <- read_sav("Choice_Test.sav")
choice_R$bought <- as.logical(choice_R$bought)
ch_sub <- Choice_Test %>%
  select(-Brand1, -Volume, -w_promo_whole_brand, -time)

sh_3 <- mlogit.data(ch_sub, choice="bought", shape="long",chid.var="choice_id", id="hh_nr", alt.var="subbrand_nr")

sh_4 <- mlogit.data(choice_test_cereals, choice="choice", shape="long",chid.var="chid", id="hushall_id", alt.var="brand_PLNB")

Base_M <- mlogit(bought ~ w_price + w_promomean, sh_3)
summary(Base_M)
Base2_M <- mlogit(bought ~ Brand2+Brand3+w_price + w_promomean|-1, sh_3)
summary(Base2_M)
Random2_M <- mlogit(bought ~ Brand2+Brand3+w_price + w_promomean|-1, sh_3, panel=TRUE, rpar = c(Brand2="n", Brand3="n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M)

Random2_M_2 <- mlogit(choice ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + sup_share + NB_intercept + loyal|-1, df, panel=TRUE, rpar = c(NB_intercept="n", sup_share="n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M)


Random3_M <- mlogit(bought ~ Brand2+Brand3+w_price + w_promomean|-1, sh_3, panel=TRUE, rpar = c(Brand2="n", Brand3="n", w_price = "n", w_promomean = "n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random3_M)

library("gmnl")
LC_2 <- gmnl(bought ~ Brand2+Brand3+w_price+w_promomean|0|0|0|1, data=sh_3, model = 'lc', Q = 2, panel = TRUE)
summary(LC_2)


AIC(LC_2)
BIC(LC_2)
LC_3 <- gmnl(bought ~ Brand2+Brand3+w_price+w_promomean|0|0|0|1, data=sh_3, model = 'lc', Q = 3, panel = TRUE)
summary(LC_3)
AIC(LC_3)
BIC(LC_3)
LC_4 <- gmnl(bought ~ Brand2+Brand3+w_price+w_promomean|0|0|0|1, data=sh_3, model = 'lc', Q = 4, panel = TRUE)
summary(LC_4)
AIC(LC_4)
BIC(LC_4)
# AIC/BIC keeps on improving. Fit is worse than with normal random coefs

```


```{r}
#rancdomcovariate
library(logitr)
m_3 <- logitr(
  data     = df,
  outcome  = 'choice',
  obsID    = 'chid',
  panelID = 'hh_id',
  pars     = c('hyperpricegain','hyperpriceloss','hyperdiscountgain', 'hyperdiscountloss', 
              'superpricegain', 'superpriceloss', 'superdiscountgain', 'superdiscountloss',
              'hyperprice', 'hyperdiscount', 'superprice','superdiscount',
              'loyal','brand_alt'),
  randPars = c(brand_alt = 'n'),
  numMultiStarts = 10
)

library(logitr)
ml_pref <- logitr(
  data     = df,
  outcome  = 'choice',
  obsID    = 'chid',
  pars     = c('hyperpricegain','hyperpriceloss','hyperdiscountgain', 'hyperdiscountloss', 
              'superpricegain', 'superpriceloss', 'superdiscountgain', 'superdiscountloss',
              'hyperprice', 'hyperdiscount', 'superprice','superdiscount',
              'loyal','sup_share','NB_intercept','PL_intercept')
)
summary(ml_pref)


ml_1 <- logitr(
  data     = df,
  outcome  = 'choice',
  obsID    = 'chid',
  pars     = c('hyperpricegain','hyperpriceloss','hyperdiscountgain', 'hyperdiscountloss', 
              'superpricegain', 'superpriceloss', 'superdiscountgain', 'superdiscountloss',
              'loyal','sup_share','NB_intercept')
)
summary(ml_1)

library(Rchoice)
logit.ran <- Rchoice(choice ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + loyal + sup_share + NB_intercept, 
                       data = df,  family = binomial('logit'),
                       ranp = c(NB_intercept = "n", sup_share = "n"),
                       panel = TRUE,index = "hushall_id")
```

```{r}
df_2 <-df[,c("hushall_id","chid","choice","brand_alt",
                            "hyperprice","hyperdiscount","superprice","superdiscount",          
                            "hyperpricegain","hyperpriceloss","hyperdiscountgain","hyperdiscountloss",
               "superpricegain","superpriceloss","superdiscountgain","superdiscountloss",
             "NB_intercept","loyal","sup_share")]

write.csv(df_2,"C:/Users/TA.4621/Desktop/2021/DiscountThreshold/WorkingRepo/data/choice_test_cereals.csv", row.names = TRUE)

choice_test_cereals <- read.csv("C:/Users/TA.4621/Desktop/2021/DiscountThreshold/WorkingRepo/data/choice_test_cereals.csv")

choice_test_cereals$bought <- as.logical(choice_test_cereals$choice)

sh_4 <- mlogit.data(choice_test_cereals, choice="bought", shape="long",chid.var="chid", id="hushall_id", alt.var="brand_alt")

Random2_M_2 <- mlogit(choice ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(NB_intercept="n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_2)


Random2_M_3 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_3)

Random2_M_4 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n", NB_intercept="n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_4)

Random2_M_5 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(hyperpricegain = "n", hyperpriceloss = "n", hyperdiscountgain = "n", hyperdiscountloss = "n", superpricegain = "n", superpriceloss = "n", superdiscountgain = "n", superdiscountloss= "n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_5)

Random2_M_5 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(hyperpricegain = "n", hyperpriceloss = "n", hyperdiscountgain = "n", hyperdiscountloss = "n", superpricegain = "n", superpriceloss = "n", superdiscountgain = "n", superdiscountloss= "n",hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_5)




```
```{r}
library("gmnl")
LC_2 <- gmnl(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|0|0|0|1, 
             data=sh_4, model = 'lc', Q = 2, panel = TRUE)
summary(LC_3)
```



```{r}
library(logitr)

mxl_pref <- logitr(
  data     = dt_unique,
  outcome  = 'choice',
  obsID    = 'choice_id',
  panelID  = 'hushall_id',
  pars     = c('hyper_pricegain','hyper_priceloss','hyper_discountgain', 'hyper_discountloss', 
              'super_pricegain', 'super_priceloss', 'super_discountgain', 'super_discountloss',
              'PL_loyal','sup_share'),
  randPars = c(hyper_pricegain = "n", hyper_priceloss = "n", hyper_discountgain = "n", hyper_discountloss = "n",
                                super_pricegain = "n", super_priceloss = "n", super_discountgain = "n", super_discountloss= "n"),
  numMultiStarts = 10
)



hyper_pricegain + hyper_priceloss + hyper_discountgain + hyper_discountloss 
                       + super_pricegain + super_priceloss + super_discountgain + super_discountloss
                       + PL_loyal + sup_share
```


