---
title: "R Notebook"
output: html_notebook
---
```{r setup and require library, include=FALSE, WARNING = FALSE}
library(dplyr) #for mutate factor level of brand
library(data.table) #for set DT checking brand
library(ggplot2)
```

```{r read data, include=FALSE}
df_hh <- read.csv("../../../../data/df_hhcoice_4cate2format.csv")
```

```{r create store information}

df_store <- read.csv("../../../../data/df_scanner_discount_threshold_filteredSKU.csv")
#Price of brand b in period t, computed as a sales-weighted average across its SKUs sold in period t
df_store$pricebeforeperunit <- df_store$spendingbeforedisc/df_store$sales_volume
df_store$finalpriceperunit <- df_store$finalspending/df_store$sales_volume
df_store$discountperunit <- df_store$totaldiscount/df_store$sales_volume
#calculated weight
weeklysalesbySKU<-setDT(df_store)[, .(totalsales_SKU=sum(sales_volume),pricebeforeperunit=mean(pricebeforeperunit),finalpriceperunit=mean(finalpriceperunit),discountperunit=mean(discountperunit)), .(produkt_id,vecka,brand_PLNB,category,format)] 
weeklysalesbybrand<-setDT(df_store)[, .(totalsales_brand=sum(sales_volume)), .(vecka,brand_PLNB,category,format)] 

df_weightcalc_SKUbrand<- merge(weeklysalesbySKU,weeklysalesbybrand, by=c("vecka","brand_PLNB","category","format"))
df_weightcalc_SKUbrand$wp <- df_weightcalc_SKUbrand$totalsales_SKU/df_weightcalc_SKUbrand$totalsales_brand
#check<-setDT(df_weightcalc_SKUbrand)[, .(totalwp=sum(wp)), .(vecka,brand_PLNB)] #check if weight sum to 1

df_weightcalc_SKUbrand$avgpricebefore <- df_weightcalc_SKUbrand$pricebeforeperunit*df_weightcalc_SKUbrand$wp
df_weightcalc_SKUbrand$avgfinalprice <- df_weightcalc_SKUbrand$finalpriceperunit*df_weightcalc_SKUbrand$wp
df_weightcalc_SKUbrand$avgdiscount <- df_weightcalc_SKUbrand$discountperunit*df_weightcalc_SKUbrand$wp
df_bybrand <- setDT(df_weightcalc_SKUbrand)[, .(totalvolume=sum(totalsales_SKU),LL=uniqueN(produkt_id),avgpricebefore=sum(avgpricebefore),avgfinalprice=sum(avgfinalprice),avgdiscount=sum(avgdiscount)), .(vecka,brand_PLNB,category,format)]

relevant_storedf <- df_bybrand[,c("vecka","avgpricebefore","avgdiscount","brand_PLNB","category","format")]

remove(list=c("df_store", "weeklysalesbySKU","weeklysalesbybrand","df_weightcalc_SKUbrand","df_bybrand")) 
```

```{r}
df_choice <- merge(df_hh,relevant_storedf, by=c("vecka","brand_PLNB","category","format"))
remove(list=c("df_hh", "relevant_storedf"))
```

```{r}
#Construct relevant variable
df_data <- df_choice[df_choice$category == "Butter",]
df_data$choice <- ifelse(df_data$brand_PLNB == "PL", 1, 0)

df_data_hypermarket <- df_data[df_data$format == "hypermarket",]
df_data_hypermarket_PL <- df_data_hypermarket[df_data_hypermarket$brand_PLNB == "PL",]
df_data_hypermarket_NB <- df_data_hypermarket[df_data_hypermarket$brand_PLNB == "NB",]
df_data_supermarket <- df_data[df_data$format == "supermarket",]
df_data_supermarket_PL <- df_data_supermarket[df_data_supermarket$brand_PLNB == "PL",]
df_data_supermarket_NB <- df_data_supermarket[df_data_supermarket$brand_PLNB == "NB",]

lag_1 <- function(x, k = 1) head(c(rep(NA, k), x), length(x))
#hypermarket PL
df_data_hypermarket_PL<-df_data_hypermarket_PL[order(df_data_hypermarket_PL$hushall_id,df_data_hypermarket_PL$vecka),]
df_data_hypermarket_PL$avgpricebefore1 <- ave(df_data_hypermarket_PL$avgpricebefore, df_data_hypermarket_PL$hushall_id, FUN= lag_1)
df_data_hypermarket_PL$avgdiscount1 <- ave(df_data_hypermarket_PL$avgdiscount, df_data_hypermarket_PL$hushall_id, FUN= lag_1)
df_data_hypermarket_PL$pricegap <- df_data_hypermarket_PL$avgpricebefore - df_data_hypermarket_PL$avgpricebefore1
df_data_hypermarket_PL$discountgap <- df_data_hypermarket_PL$avgdiscount - df_data_hypermarket_PL$avgdiscount1
df_data_hypermarket_PL$pricegaploss <- ifelse(df_data_hypermarket_PL$pricegap >0, -df_data_hypermarket_PL$pricegap, 0)
df_data_hypermarket_PL$pricegapgain <- ifelse(df_data_hypermarket_PL$pricegap <0, df_data_hypermarket_PL$pricegap, 0)
df_data_hypermarket_PL$discountgaploss <- ifelse(df_data_hypermarket_PL$discountgap <0, -df_data_hypermarket_PL$discountgap, 0)
df_data_hypermarket_PL$discountgapgain <- ifelse(df_data_hypermarket_PL$discountgap >0, df_data_hypermarket_PL$discountgap, 0)
#hypermarket NB
df_data_hypermarket_NB<-df_data_hypermarket_NB[order(df_data_hypermarket_NB$hushall_id,df_data_hypermarket_NB$vecka),]
df_data_hypermarket_NB$avgpricebefore1 <- ave(df_data_hypermarket_NB$avgpricebefore, df_data_hypermarket_NB$hushall_id, FUN= lag_1)
df_data_hypermarket_NB$avgdiscount1 <- ave(df_data_hypermarket_NB$avgdiscount, df_data_hypermarket_NB$hushall_id, FUN= lag_1)
df_data_hypermarket_NB$pricegap <- df_data_hypermarket_NB$avgpricebefore - df_data_hypermarket_NB$avgpricebefore1
df_data_hypermarket_NB$discountgap <- df_data_hypermarket_NB$avgdiscount - df_data_hypermarket_NB$avgdiscount1
df_data_hypermarket_NB$pricegaploss <- ifelse(df_data_hypermarket_NB$pricegap >0, -df_data_hypermarket_NB$pricegap, 0)
df_data_hypermarket_NB$pricegapgain <- ifelse(df_data_hypermarket_NB$pricegap <0, df_data_hypermarket_NB$pricegap, 0)
df_data_hypermarket_NB$discountgaploss <- ifelse(df_data_hypermarket_NB$discountgap <0, -df_data_hypermarket_NB$discountgap, 0)
df_data_hypermarket_NB$discountgapgain <- ifelse(df_data_hypermarket_NB$discountgap >0, df_data_hypermarket_NB$discountgap, 0)
#supermarket PL
df_data_supermarket_PL<-df_data_supermarket_PL[order(df_data_supermarket_PL$hushall_id,df_data_supermarket_PL$vecka),]
df_data_supermarket_PL$avgpricebefore1 <- ave(df_data_supermarket_PL$avgpricebefore, df_data_supermarket_PL$hushall_id, FUN= lag_1)
df_data_supermarket_PL$avgdiscount1 <- ave(df_data_supermarket_PL$avgdiscount, df_data_supermarket_PL$hushall_id, FUN= lag_1)
df_data_supermarket_PL$pricegap <- df_data_supermarket_PL$avgpricebefore - df_data_supermarket_PL$avgpricebefore1
df_data_supermarket_PL$discountgap <- df_data_supermarket_PL$avgdiscount - df_data_supermarket_PL$avgdiscount1
df_data_supermarket_PL$pricegaploss <- ifelse(df_data_supermarket_PL$pricegap >0, -df_data_supermarket_PL$pricegap, 0)
df_data_supermarket_PL$pricegapgain <- ifelse(df_data_supermarket_PL$pricegap <0, df_data_supermarket_PL$pricegap, 0)
df_data_supermarket_PL$discountgaploss <- ifelse(df_data_supermarket_PL$discountgap <0, -df_data_supermarket_PL$discountgap, 0)
df_data_supermarket_PL$discountgapgain <- ifelse(df_data_supermarket_PL$discountgap >0, df_data_supermarket_PL$discountgap, 0)
#supermarket NB
df_data_supermarket_NB<-df_data_supermarket_NB[order(df_data_supermarket_NB$hushall_id,df_data_supermarket_NB$vecka),]
df_data_supermarket_NB$avgpricebefore1 <- ave(df_data_supermarket_NB$avgpricebefore, df_data_supermarket_NB$hushall_id, FUN= lag_1)
df_data_supermarket_NB$avgdiscount1 <- ave(df_data_supermarket_NB$avgdiscount, df_data_supermarket_NB$hushall_id, FUN= lag_1)
df_data_supermarket_NB$pricegap <- df_data_supermarket_NB$avgpricebefore - df_data_supermarket_NB$avgpricebefore1
df_data_supermarket_NB$discountgap <- df_data_supermarket_NB$avgdiscount - df_data_supermarket_NB$avgdiscount1
df_data_supermarket_NB$pricegaploss <- ifelse(df_data_supermarket_NB$pricegap >0, -df_data_supermarket_NB$pricegap, 0)
df_data_supermarket_NB$pricegapgain <- ifelse(df_data_supermarket_NB$pricegap <0, df_data_supermarket_NB$pricegap, 0)
df_data_supermarket_NB$discountgaploss <- ifelse(df_data_supermarket_NB$discountgap <0, -df_data_supermarket_NB$discountgap, 0)
df_data_supermarket_NB$discountgapgain <- ifelse(df_data_supermarket_NB$discountgap >0, df_data_supermarket_NB$discountgap, 0)

df_data_merge <- data.table(rbind(df_data_hypermarket_PL,df_data_hypermarket_NB,df_data_supermarket_PL,df_data_supermarket_NB))

#create seperate variable for hypermarket and supermarket
df_data_merge$hyper_pricegain <- ifelse(df_data_merge$pricegapgain >0 & df_data_merge$format == "hypermarket" , df_data_merge$pricegapgain, 0)
df_data_merge$hyper_priceloss <- ifelse(df_data_merge$pricegaploss >0 & df_data_merge$format == "hypermarket" , df_data_merge$pricegaploss, 0)
df_data_merge$hyper_discountgain <- ifelse(df_data_merge$discountgapgain >0 & df_data_merge$format == "hypermarket" , df_data_merge$discountgapgain, 0)
df_data_merge$hyper_discountloss <- ifelse(df_data_merge$discountgaploss >0 & df_data_merge$format == "hypermarket" , df_data_merge$discountgaploss, 0)
df_data_merge$super_pricegain <- ifelse(df_data_merge$pricegapgain >0 & df_data_merge$format == "supermarket" , df_data_merge$pricegapgain, 0)
df_data_merge$super_priceloss <- ifelse(df_data_merge$pricegaploss >0 & df_data_merge$format == "supermarket" , df_data_merge$pricegaploss, 0)
df_data_merge$super_discountgain <- ifelse(df_data_merge$discountgapgain >0 & df_data_merge$format == "supermarket" , df_data_merge$discountgapgain, 0)
df_data_merge$super_discountloss <- ifelse(df_data_merge$discountgaploss >0 & df_data_merge$format == "supermarket" , df_data_merge$discountgaploss, 0)

#loyalty variable
df_data_merge<-df_data_merge[order(df_data_merge$hushall_id,df_data_merge$vecka),]
alpha_loyal = 0.89
df_data_merge$PL_loyal1 <- ave(df_data_merge$choice, df_data_merge$hushall_id, FUN= lag_1)
df_data_merge$PL_loyal <- alpha_loyal*df_data_merge$PL_loyal1 + (1-alpha_loyal)*df_data_merge$choice
df_data_merge$NB_intercept <- ifelse(df_data_merge$brand_PLNB == "NB", 1, 0)

df_data_merge$supermarket_shop <- ifelse(df_data_merge$format == "supermarket", 1, 0)
df_data_merge$shoppingtime <- 1
#df_data_merge$sup_accumulate1 <- ave(df_data_merge$sup_accumulate, df_data_merge$hushall_id, FUN= lag_1)
#df_data_merge$shoppingtime1 <- ave(df_data_merge$shoppingtime, df_data_merge$hushall_id, FUN= lag_1)
#df_data_merge$sup_accumulate_t <- df_data_merge$sup_accumulate + df_data_merge$sup_accumulate1
#df_data_merge$shoppingtime_t <- df_data_merge$shoppingtime + df_data_merge$shoppingtime[-1]

df_data_merge[, TotalShoppinttime := cumsum(shift(shoppingtime, fill = 1)), by = hushall_id]
df_data_merge[, Supermarkettime := cumsum(shift(supermarket_shop, fill = 0)), by = hushall_id]
df_data_merge$sup_share <- df_data_merge$supermarket_shop/df_data_merge$TotalShoppinttime

df_data_merge <- na.omit(df_data_merge) #We drop first week

df
```

```{r run choice model}
library(Rchoice)

## Poisson Model with Random Parameters
logit.ran <- Rchoice(choice ~ hyper_pricegain + hyper_priceloss + hyper_discountgain + hyper_discountloss 
                       + super_pricegain + super_priceloss + super_discountgain + super_discountloss
                       + PL_loyal + sup_share, 
                       data = df_data_merge,  family = binomial('logit'),
                       ranp = c(hyper_pricegain = "n", hyper_priceloss = "n", hyper_discountgain = "n", hyper_discountloss = "n",
                                super_pricegain = "n", super_priceloss = "n", super_discountgain = "n", super_discountloss= "n"),
                       panel = TRUE,index = "hushall_id")
summary(poisson.ran)     

```


