---
title: "R Notebook"
output: html_notebook
---
```{r setup and require library, include=FALSE, WARNING = FALSE}
library(mlogit) #for estimation
```

```{r read data, include=FALSE}
df_butter_choice <- read.csv("../../../../data/df_butter_choice.csv")
df_cereals_choice <- read.csv("../../../../data/df_cereals_choice.csv")
df_cream_choice <- read.csv("../../../../data/df_cream_choice.csv")
df_lactosefree_choice <- read.csv("../../../../data/df_lactosefree_choice.csv")
```

```{r fit data into mlogit form}
df_butter_choice$bought <- as.logical(df_butter_choice$choice)
df_butter <- mlogit.data(df_butter_choice, choice="bought", shape="long",chid.var="chid", id="hushall_id", alt.var="brand_alt")

df_cereals_choice$bought <- as.logical(df_cereals_choice$choice)
df_cereals <- mlogit.data(df_cereals_choice, choice="bought", shape="long",chid.var="chid", id="hushall_id", alt.var="brand_alt")

df_cream_choice$bought <- as.logical(df_cream_choice$choice)
df_cream <- mlogit.data(df_cream_choice, choice="bought", shape="long",chid.var="chid", id="hushall_id", alt.var="brand_alt")

df_lactosefree_choice$bought <- as.logical(df_lactosefree_choice$choice)
df_lactosefree <- mlogit.data(df_lactosefree_choice, choice="bought", shape="long",chid.var="chid", id="hushall_id", alt.var="brand_alt")
```


```{r}
random_m_butter <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_butter, panel=TRUE, 
                       rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n",
                                NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_butter)

random_m_cereals <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_cereals, panel=TRUE, 
                       rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n",
                                NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_cereals)

random_m_cream <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_cream, panel=TRUE, 
                       rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n",
                                NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_cream)

random_m_lactosefree <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_lactosefree, panel=TRUE, 
                       rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n",
                                NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_lactosefree)
```

## TEST with less random parameter

```{r}
random_m_butter_0 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_butter, panel=TRUE, 
                       rpar = c(loyal = "n", NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_butter_0)

random_m_cereals_0 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_cereals, panel=TRUE, 
                       rpar = c(loyal = "n", NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_cereals_0)

random_m_cream_0 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_cream, panel=TRUE, 
                      rpar = c(loyal = "n", NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_cream_0)

random_m_lactosefree_0 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_lactosefree, panel=TRUE, 
                       rpar = c(loyal = "n", NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_lactosefree_0)
```







##### APPENDIX OF ESTIMATION VARIATION #######

```{r using lme4 package}
library(lme4)
m_1 <- glmer(choice ~ 0 + hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + sup_share + NB_intercept + loyal  + (1 | hushall_id), data = df, family = binomial, control = glmerControl(optimizer = "bobyqa"),nAGQ = 10)

m_nolevel <- glmer(choice ~ 0 + hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + NB_intercept + loyal  + (1 | hushall_id), data = df, family = binomial, control = glmerControl(optimizer = "bobyqa"),nAGQ = 10)
```
```{r}
choice_R <- read_sav("Choice_Test.sav")
choice_R$bought <- as.logical(choice_R$bought)
ch_sub <- Choice_Test %>%
  select(-Brand1, -Volume, -w_promo_whole_brand, -time)

sh_3 <- mlogit.data(ch_sub, choice="bought", shape="long",chid.var="choice_id", id="hh_nr", alt.var="subbrand_nr")

sh_4 <- mlogit.data(choice_test_cereals, choice="choice", shape="long",chid.var="chid", id="hushall_id", alt.var="brand_PLNB")

Base_M <- mlogit(bought ~ w_price + w_promomean, sh_3)
summary(Base_M)
Base2_M <- mlogit(bought ~ Brand2+Brand3+w_price + w_promomean|-1, sh_3)
summary(Base2_M)
Random2_M <- mlogit(bought ~ Brand2+Brand3+w_price + w_promomean|-1, sh_3, panel=TRUE, rpar = c(Brand2="n", Brand3="n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M)

Random2_M_2 <- mlogit(choice ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + sup_share + NB_intercept + loyal|-1, df, panel=TRUE, rpar = c(NB_intercept="n", sup_share="n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M)


Random3_M <- mlogit(bought ~ Brand2+Brand3+w_price + w_promomean|-1, sh_3, panel=TRUE, rpar = c(Brand2="n", Brand3="n", w_price = "n", w_promomean = "n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random3_M)

library("gmnl")
LC_2 <- gmnl(bought ~ Brand2+Brand3+w_price+w_promomean|0|0|0|1, data=sh_3, model = 'lc', Q = 2, panel = TRUE)
summary(LC_2)


AIC(LC_2)
BIC(LC_2)
LC_3 <- gmnl(bought ~ Brand2+Brand3+w_price+w_promomean|0|0|0|1, data=sh_3, model = 'lc', Q = 3, panel = TRUE)
summary(LC_3)
AIC(LC_3)
BIC(LC_3)
LC_4 <- gmnl(bought ~ Brand2+Brand3+w_price+w_promomean|0|0|0|1, data=sh_3, model = 'lc', Q = 4, panel = TRUE)
summary(LC_4)
AIC(LC_4)
BIC(LC_4)
# AIC/BIC keeps on improving. Fit is worse than with normal random coefs

```


```{r using logitr}
#rancdomcovariate
library(logitr)
m_3 <- logitr(
  data     = df,
  outcome  = 'choice',
  obsID    = 'chid',
  panelID = 'hh_id',
  pars     = c('hyperpricegain','hyperpriceloss','hyperdiscountgain', 'hyperdiscountloss', 
              'superpricegain', 'superpriceloss', 'superdiscountgain', 'superdiscountloss',
              'hyperprice', 'hyperdiscount', 'superprice','superdiscount',
              'loyal','brand_alt'),
  randPars = c(brand_alt = 'n'),
  numMultiStarts = 10
)

library(logitr)
ml_pref <- logitr(
  data     = df,
  outcome  = 'choice',
  obsID    = 'chid',
  pars     = c('hyperpricegain','hyperpriceloss','hyperdiscountgain', 'hyperdiscountloss', 
              'superpricegain', 'superpriceloss', 'superdiscountgain', 'superdiscountloss',
              'hyperprice', 'hyperdiscount', 'superprice','superdiscount',
              'loyal','sup_share','NB_intercept','PL_intercept')
)
summary(ml_pref)


ml_1 <- logitr(
  data     = df,
  outcome  = 'choice',
  obsID    = 'chid',
  pars     = c('hyperpricegain','hyperpriceloss','hyperdiscountgain', 'hyperdiscountloss', 
              'superpricegain', 'superpriceloss', 'superdiscountgain', 'superdiscountloss',
              'loyal','sup_share','NB_intercept')
)
summary(ml_1)

library(Rchoice)
logit.ran <- Rchoice(choice ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + loyal + sup_share + NB_intercept, 
                       data = df,  family = binomial('logit'),
                       ranp = c(NB_intercept = "n", sup_share = "n"),
                       panel = TRUE,index = "hushall_id")
```

```{r}


Random2_M_3 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_3)

Random2_M_4 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n", NB_intercept="n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_4)

Random2_M_5 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(hyperpricegain = "n", hyperpriceloss = "n", hyperdiscountgain = "n", hyperdiscountloss = "n", superpricegain = "n", superpriceloss = "n", superdiscountgain = "n", superdiscountloss= "n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_5)

Random2_M_5 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, sh_4, panel=TRUE, rpar = c(hyperpricegain = "n", hyperpriceloss = "n", hyperdiscountgain = "n", hyperdiscountloss = "n", superpricegain = "n", superpriceloss = "n", superdiscountgain = "n", superdiscountloss= "n",hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n"),correlation = FALSE, R = 100, Halton=NA)
summary(Random2_M_5)




```
```{r}
library("gmnl")
LC_2 <- gmnl(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|0|0|0|1, 
             data=sh_4, model = 'lc', Q = 2, panel = TRUE)
summary(LC_3)
```



```{r}
library(logitr)

mxl_pref <- logitr(
  data     = dt_unique,
  outcome  = 'choice',
  obsID    = 'choice_id',
  panelID  = 'hushall_id',
  pars     = c('hyper_pricegain','hyper_priceloss','hyper_discountgain', 'hyper_discountloss', 
              'super_pricegain', 'super_priceloss', 'super_discountgain', 'super_discountloss',
              'PL_loyal','sup_share'),
  randPars = c(hyper_pricegain = "n", hyper_priceloss = "n", hyper_discountgain = "n", hyper_discountloss = "n",
                                super_pricegain = "n", super_priceloss = "n", super_discountgain = "n", super_discountloss= "n"),
  numMultiStarts = 10
)



hyper_pricegain + hyper_priceloss + hyper_discountgain + hyper_discountloss 
                       + super_pricegain + super_priceloss + super_discountgain + super_discountloss
                       + PL_loyal + sup_share
```


