---
title: "R Notebook"
output: html_notebook
---
```{r setup and require library, include=FALSE, WARNING = FALSE}
library(mlogit) #for estimation
```

```{r read data, include=FALSE}
df_butter_choice <- read.csv("../../../../data/EMAC2024_2_df_butter_choice.csv")
```

```{r fit data into mlogit form}
df_butter_choice$bought <- as.logical(df_butter_choice$choice)
df_butter <- mlogit.data(df_butter_choice, choice="bought", shape="long",chid.var="chid", id="hushall_id", alt.var="brand_alt")
```


```{r}
random_m_butter <- mlogit(bought ~ hyperpricegain + hyperpriceloss
                       + superpricegain + superpriceloss
                       + hyperprice + hyperdiscount + superprice + superdiscount + conveprice + convediscount
                       + Nonfocal_intercept + loyal_nonfocal|-1, df_butter, panel=TRUE, 
                       rpar = c(hyperprice = "n", hyperdiscount = "n", superprice = "n", superdiscount = "n", 
                                conveprice = "n", convediscount = "n",
                                Nonfocal_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_butter)

#Need to reconstruct the format loyalty
```

## TEST with less random parameter

```{r}
random_m_butter_0 <- mlogit(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|-1, df_butter, panel=TRUE, 
                       rpar = c(loyal = "n", NB_intercept="n"),
                       correlation = FALSE, R = 100, Halton=NA)
summary(random_m_butter_0)

```







```{r}
library("gmnl")
LC_2 <- gmnl(bought ~ hyperpricegain + hyperpriceloss + hyperdiscountgain + hyperdiscountloss 
                       + superpricegain + superpriceloss + superdiscountgain + superdiscountloss
                       + hyperprice + hyperdiscount + superprice + superdiscount
                       + NB_intercept + loyal|0|0|0|1, 
             data=sh_4, model = 'lc', Q = 2, panel = TRUE)
summary(LC_3)
```



```{r}
library(logitr)

mxl_pref <- logitr(
  data     = dt_unique,
  outcome  = 'choice',
  obsID    = 'choice_id',
  panelID  = 'hushall_id',
  pars     = c('hyper_pricegain','hyper_priceloss','hyper_discountgain', 'hyper_discountloss', 
              'super_pricegain', 'super_priceloss', 'super_discountgain', 'super_discountloss',
              'PL_loyal','sup_share'),
  randPars = c(hyper_pricegain = "n", hyper_priceloss = "n", hyper_discountgain = "n", hyper_discountloss = "n",
                                super_pricegain = "n", super_priceloss = "n", super_discountgain = "n", super_discountloss= "n"),
  numMultiStarts = 10
)



hyper_pricegain + hyper_priceloss + hyper_discountgain + hyper_discountloss 
                       + super_pricegain + super_priceloss + super_discountgain + super_discountloss
                       + PL_loyal + sup_share
```


