---
title: "Managebrandandcategorydata for (aggregate model) discount loss threshold"
author: "Ned"
date: "22/12/2021"
output: pdf_document
---

```{r setup and require library, include=FALSE, WARNING = FALSE}
library(dplyr) #for mutate factor level of brand
library(data.table) #for set DT checking brand
library(ggplot2)
```

```{r read data, include=FALSE}
df <- read.csv("../../../../data/df_scanner_discount_threshold_filteredSKU.csv")
df_holiday <- read.csv("../../../../data/weeklyholiday.csv")
```


#Function of creating relevant variables

```{r create trend variable, include=FALSE}
#very bad way of doing
df_holiday<-df_holiday [order(df_holiday$vecka),]
df_holiday$trend <- seq(1:length(unique(df_holiday$vecka)))
```

  We create a function ``genrelevantvar_perSKU`` that generates 1) calculate aggregate brand price/discount/unit sales of each brand from sales-weighted average across its SKUs sold in period t 

```{r calculate the brand price related variables and linelength or our main IV, echo=FALSE}
genrelevantvar_perSKU <- function(df,format,category){
  df <- df[df$category == category & df$format == format,]
  
#Price of brand b in period t, computed as a sales-weighted average across its SKUs sold in period t
df$pricebeforeperunit <- df$spendingbeforedisc/df$sales_volume
df$finalpriceperunit <- df$finalspending/df$sales_volume
df$discountperunit <- df$totaldiscount/df$sales_volume
df$nonpricecampaign <- ifelse(df$totaldiscount == 0 & df$week_campaign > 0, 1, 0)
df$pricecampaign <- ifelse(df$totaldiscount != 0 & df$week_campaign > 0, 1, 0)
#calculated weight
weeklysalesbySKU<-setDT(df)[, .(totalsales_SKU=sum(sales_volume),pricebeforeperunit=mean(pricebeforeperunit),finalpriceperunit=mean(finalpriceperunit),discountperunit=mean(discountperunit)), .(produkt_id,vecka,brand_PLNB)] 
weeklysalesbybrand<-setDT(df)[, .(totalsales_brand=sum(sales_volume),LL=uniqueN(produkt_id),totalnonpricecampaign=sum(nonpricecampaign),totalpricecampaign=sum(pricecampaign)), .(vecka,brand_PLNB)] 

df_weightcalc_SKUbrand<- merge(weeklysalesbySKU,weeklysalesbybrand, by=c("vecka","brand_PLNB"))
df_weightcalc_SKUbrand$wp <- df_weightcalc_SKUbrand$totalsales_SKU/df_weightcalc_SKUbrand$totalsales_brand
#check<-setDT(df_weightcalc_SKUbrand)[, .(totalwp=sum(wp)), .(vecka,brand_PLNB)] #check if weight sum to 1

df_weightcalc_SKUbrand$avgpricebefore <- df_weightcalc_SKUbrand$pricebeforeperunit*df_weightcalc_SKUbrand$wp
df_weightcalc_SKUbrand$avgfinalprice <- df_weightcalc_SKUbrand$finalpriceperunit*df_weightcalc_SKUbrand$wp
df_weightcalc_SKUbrand$avgdiscount <- df_weightcalc_SKUbrand$discountperunit*df_weightcalc_SKUbrand$wp
df_bybrand <- setDT(df_weightcalc_SKUbrand)[, .(totalvolume=sum(totalsales_SKU),LL=uniqueN(produkt_id),avgpricebefore=sum(avgpricebefore),avgfinalprice=sum(avgfinalprice),avgdiscount=sum(avgdiscount),totalbrandnonpricecampaign=mean(totalnonpricecampaign),totalbrandpricecampaign=mean(totalpricecampaign)), .(vecka,brand_PLNB)]

brand_campaign_week <- setDT(df_bybrand)[, .(totalnonpricecampaign=sum(totalbrandnonpricecampaign),totalpricecampaign=sum(totalbrandpricecampaign)), .(vecka)]
brand_campaign_week$totalcampaign <- brand_campaign_week$totalnonpricecampaign+brand_campaign_week$totalpricecampaign
df_bybrand <- merge(df_bybrand,brand_campaign_week, by=c("vecka"))

# df_bybrand$pricecampaignintensity <- ((df_bybrand$totalbrandpricecampaign/df_bybrand$totalcampaign)*100)
# df_bybrand$nonpricecampaignintensity <- ((df_bybrand$totalbrandnonpricecampaign/df_bybrand$totalcampaign)*100)

weeklysalesbybrand_PL <- df_bybrand[df_bybrand$brand_PLNB == "PL",]
weeklysalesbybrand_NB <- df_bybrand[df_bybrand$brand_PLNB == "NB",]

#choose NB price as comp price
colnames(weeklysalesbybrand_NB)[colnames(weeklysalesbybrand_NB) == "avgfinalprice"] ="avgcompfinalprice"
relevant_NB <- weeklysalesbybrand_NB[,c("vecka","avgcompfinalprice")]

df_bybrand <- merge(weeklysalesbybrand_PL,relevant_NB, by=c("vecka"))

#create own depth
df_bybrand$depth <- df_bybrand$avgdiscount/df_bybrand$avgpricebefore
df_bybrand$nondepth <- (1-df_bybrand$depth)


#generate lag variables
lag_1 <- function(x, k = 1) head(c(rep(NA, k), x), length(x))
df_bybrand<-df_bybrand [order(df_bybrand$brand_PLNB,df_bybrand$vecka),]
df_bybrand$totalvolume1 <- ave(df_bybrand$totalvolume, df_bybrand$brand_PLNB, FUN= lag_1)
df_bybrand$LL1 <- ave(df_bybrand$LL, df_bybrand$brand_PLNB, FUN= lag_1)
df_bybrand$avgfinalprice1 <- ave(df_bybrand$avgfinalprice, df_bybrand$brand_PLNB, FUN= lag_1)
df_bybrand$avgpricebefore1 <- ave(df_bybrand$avgpricebefore, df_bybrand$brand_PLNB, FUN= lag_1)
df_bybrand$avgdiscount1 <- ave(df_bybrand$avgdiscount, df_bybrand$brand_PLNB, FUN= lag_1)
df_bybrand$nondepth1 <- ave(df_bybrand$nondepth, df_bybrand$brand_PLNB, FUN= lag_1)
df_bybrand$avgcompfinalprice1 <- ave(df_bybrand$avgcompfinalprice, df_bybrand$brand_PLNB, FUN= lag_1)
# df_bybrand$pricecampaignintensity1 <- ave(df_bybrand$pricecampaignintensity, df_bybrand$brand_PLNB, FUN= lag_1)
df_bybrand$logavgdiscount <- log(df_bybrand$avgdiscount+1)
df_bybrand$logavgdiscount1 <- ave(df_bybrand$logavgdiscount, df_bybrand$brand_PLNB, FUN= lag_1)

#create the first difference of (log) variables
df_bybrand <- na.omit(df_bybrand) #We drop week 0
df_bybrand$dtotalvolume <- (df_bybrand$totalvolume)-(df_bybrand$totalvolume1)
df_bybrand$dlogtotalvolume <- log(df_bybrand$totalvolume)-log(df_bybrand$totalvolume1)
df_bybrand$davgfinalprice <- (df_bybrand$avgfinalprice)-(df_bybrand$avgfinalprice1)
df_bybrand$davgpricebefore <- (df_bybrand$avgpricebefore)-(df_bybrand$avgpricebefore1)
df_bybrand$dlogavgfinalprice <- log(df_bybrand$avgfinalprice)-log(df_bybrand$avgfinalprice1)
df_bybrand$dlogavgpricebefore <- log(df_bybrand$avgpricebefore)-log(df_bybrand$avgpricebefore1)
df_bybrand$davgcompfinalprice = (df_bybrand$avgcompfinalprice) - (df_bybrand$avgcompfinalprice1)
df_bybrand$davgdiscount <- (df_bybrand$avgdiscount)-(df_bybrand$avgdiscount1)
df_bybrand$dlogavgdiscount <- log(df_bybrand$avgdiscount+1)-log(df_bybrand$avgdiscount1+1)
df_bybrand$dnondepth <- df_bybrand$nondepth-df_bybrand$nondepth1
df_bybrand$dlognondepth <- log(df_bybrand$nondepth)-log(df_bybrand$nondepth1)
df_bybrand$dlogLL = log(df_bybrand$LL) - log(df_bybrand$LL1)
df_bybrand$dlogavgcompfinalprice = log(df_bybrand$avgcompfinalprice) - log(df_bybrand$avgcompfinalprice1)
# df_bybrand$dpricecampaignintensity = df_bybrand$pricecampaignintensity - df_bybrand$pricecampaignintensity1


df_bybrand$logtotalvolume <- log(df_bybrand$totalvolume)
df_bybrand$logavgpricebefore <- log(df_bybrand$avgpricebefore)
df_bybrand$logavgcompfinalprice <- log(df_bybrand$avgcompfinalprice)
df_bybrand$logavgfinalprice <- log(df_bybrand$avgfinalprice)

#create copula
make_copula <- function(x) {
		if (length(unique(x))==1) return(as.numeric(rep(NA, length(x))))
		return(ifelse(ecdf(x)(x)==1, qnorm(1-.0000001), qnorm(ecdf(x)(x))))}
#This functions transforms a variable (condition: non-normally distributed) to its copula-correction term which can be entered in model estimation. See Park and Gupta (2012, Marketing Science)
df_bybrand$cop_logavgpricebefore <- make_copula(log((df_bybrand$avgpricebefore)))
df_bybrand$cop_logdiscount <- make_copula(df_bybrand$logavgdiscount)
df_bybrand$cop_avgpricebefore <- make_copula((df_bybrand$avgpricebefore))
df_bybrand$cop_discount <- make_copula(df_bybrand$avgdiscount)
df_bybrand$cop_lognondepth<- make_copula(log(df_bybrand$nondepth))
df_bybrand$cop_logavgfinalprice<- make_copula(log(df_bybrand$avgfinalprice))

#create a holiday variable
df_holiday$vecka <- as.factor(df_holiday$vecka)
df_bybrand$vecka <- as.factor(df_bybrand$vecka)

df_bybrand <- merge(df_bybrand,df_holiday[,2:4], by=c("vecka"))

#create separate price/discount ><0 for indicator function
df_bybrand$dlogavgpricebefore_loss <- ifelse(df_bybrand$dlogavgpricebefore > 0, df_bybrand$dlogavgpricebefore, 0)
df_bybrand$dlogavgpricebefore_gain <- ifelse(df_bybrand$dlogavgpricebefore < 0, df_bybrand$dlogavgpricebefore, 0)
df_bybrand$dlognondepth_loss <- ifelse(df_bybrand$dlognondepth > 0, df_bybrand$dlognondepth, 0)
df_bybrand$dlognondepth_gain <- ifelse(df_bybrand$dlognondepth < 0, df_bybrand$dlognondepth, 0)
    

#convert format back
df_bybrand$format <- format
df_bybrand$category <- category


return(df_bybrand)
}

```

```{r esimation function and plotting mathematically decompose}
discountnonlinearest_PL_nothreshold_depth <- function(df,alpha_l_price,alpha_l_nondepth){
  
df <- df[df$brand == "PL",]
LS_nonlinear <- function(parvec){
  
  F_H_L <- 1/(1+exp(-gamma*(df$dlogavgpricebefore)))
  F_D_L <- 1/(1+exp(-gamma*(df$dlognondepth)))
  
  ut <- df$dlogtotalvolume - (parvec[1] + (parvec[2]+ parvec[3]*F_H_L)*df$dlogavgpricebefore
                                  + (parvec[4] + parvec[5]*F_D_L)*df$dlognondepth
                            + parvec[6]*df$dlogavgcompfinalprice
                            + parvec[7]*((log(df$totalvolume1))+parvec[8]*log(df$avgpricebefore1)+parvec[9]*log(df$nondepth1))
                            + parvec[10]*df$holiday)
  logL <- sum (-0.5* log(parvec[11]) - 0.5*ut^2/parvec[11] )
  return(-logL)
}

  gamma <- 1000 #assumed
  
lm_full_linear <- lm(dlogtotalvolume ~ dlogavgpricebefore + dlognondepth + dlogavgcompfinalprice + log(totalvolume1) + log(avgpricebefore1) + log(nondepth1) + holiday,data=df)

#summary(lm_full_linear)

c_full_lm <- summary(lm_full_linear)$coefficients[1,1]
alpha_0_full_lm <- summary(lm_full_linear)$coefficients[2,1]
alpha_0_disc_lm <- summary(lm_full_linear)$coefficients[3,1]
alpha_compprice <- summary(lm_full_linear)$coefficients[4,1]
phi_1_full_lm <- summary(lm_full_linear)$coefficients[5,1]
phi_2_full_lm <- (summary(lm_full_linear)$coefficients[6,1])/(summary(lm_full_linear)$coefficients[5,1]) 
phi_3_full_lm <- (summary(lm_full_linear)$coefficients[7,1])/(summary(lm_full_linear)$coefficients[5,1])
alpha_holiday <- summary(lm_full_linear)$coefficients[8,1]

print(paste("Linearmodel_price_coef:",summary(lm_full_linear)$coefficients[2,1],
            "Linearmodel_price_se:",summary(lm_full_linear)$coefficients[2,2],
            "pv_price:",summary(lm_full_linear)$coefficients[2,4],
            "Linearmodel_nondepth_coef:",summary(lm_full_linear)$coefficients[3,1],
            "Linearmodel_nondepth_se:",summary(lm_full_linear)$coefficients[3,2],
            "pv_nondepth:",summary(lm_full_linear)$coefficients[3,4]))

  parvec_1 <- c_full_lm
  parvec_2 <- alpha_0_full_lm
  parvec_3 <- alpha_l_price
  parvec_4 <-  alpha_0_disc_lm
  parvec_5 <- alpha_l_nondepth
  parvec_6 <- alpha_compprice
  parvec_7 <- phi_1_full_lm
  parvec_8 <- phi_2_full_lm
  parvec_9 <- phi_3_full_lm
  parvec_10 <- alpha_holiday
  parvec_11 <- summary(lm_full_linear)$sigma

  
Start_v_LS <- c(parvec_1,parvec_2,parvec_3,parvec_4,parvec_5,parvec_6,parvec_7,parvec_8,parvec_9,parvec_10,parvec_11)



LS_logL_nonlinear_his_constraint = optim(Start_v_LS,
                  fn = LS_nonlinear, # function to maximize
                  method = "BFGS",
                  control = list(fnscale = 1), # minimize the function
                  hessian = T # calculate Hessian matrix because we will need for confidence intervals
                  ) 


par_LS.est<-LS_logL_nonlinear_his_constraint$par


  n <- dim(df)[1]
  k <- length(Start_v_LS)


MSE_calculated <- LS_logL_nonlinear_his_constraint$value/(n-k)


OI<-solve(LS_logL_nonlinear_his_constraint$hessian)
par_LS.se<-sqrt(diag(OI))

Start_v_LS
par_LS.est

par_LS_name <- c("constant", "price_elas","price_elas_loss","disc_elas","disc_elas_loss",
                 "compprice","correction_vol","correction_price","correction_discount","holiday","sigma")
par_LS <- data.table(cbind(par_LS_name,par_LS.est,par_LS.se))
par_LS$tstat <- as.numeric(par_LS$par_LS.est)/as.numeric(par_LS$par_LS.se)

par_LS$format <- df$format[1]
par_LS$category <-df$category[1]


print(paste("Linearmodel_sigma:",summary(lm_full_linear)$sigma,"Nonlinearmodel_sigma:",par_LS.est[11]))


#function for plot value
dlogprice_values <- seq(-0.15, 0.15, by = 0.001)
nplot <- dim(t(dlogprice_values))[2]
alpha0 <- par_LS.est[2]
alpha_L <- par_LS.est[3]
alpha0_disc <- par_LS.est[4]
alpha_L_disc <- par_LS.est[5]

NLPE_pricebefore <- function(dlogavgpricebefore)
{( alpha0 + alpha_L*(1+ exp(-gamma*(dlogavgpricebefore)))^-1)*dlogavgpricebefore}
NLPE_discount <- function(dlogavgdiscount)
{( alpha0_disc + alpha_L_disc*(1+ exp(-gamma*(dlogavgdiscount)))^-1)*dlogavgdiscount}
NLPE_values_pricebefore <- NLPE_pricebefore(dlogavgpricebefore=dlogprice_values)
NLPE_values_discount <- NLPE_discount(dlogavgdiscount =dlogprice_values)
format <- c(rep(as.character(df$format[1]), nplot))
category <- c(rep(as.character(df$category[1]), nplot))

plot <- data.table(cbind(dlogprice_values,NLPE_values_pricebefore,NLPE_values_discount,format,category))

results <- list(par_LS,plot) #the result returns plot of elasticity [[2]] and estimate [[2]]


return(results)
}
```




#Prepare data for estimating aggregate
```{r}
butter_hyper_PL <- genrelevantvar_perSKU(df,format = "hypermarket",category ="Butter")
butter_super_PL <- genrelevantvar_perSKU(df,format = "supermarket",category ="Butter")

cereals_hyper_PL <- genrelevantvar_perSKU(df,format = "hypermarket",category ="Cereals")
cereals_super_PL <- genrelevantvar_perSKU(df,format = "supermarket",category ="Cereals")

cream_hyper_PL <- genrelevantvar_perSKU(df,format = "hypermarket",category ="Cream")
cream_super_PL <- genrelevantvar_perSKU(df,format = "supermarket",category ="Cream")

lactosefree_hyper_PL <- genrelevantvar_perSKU(df,format = "hypermarket",category ="LactoseFree")
lactosefree_super_PL <- genrelevantvar_perSKU(df,format = "supermarket",category ="LactoseFree")
```

```{r eval=FALSE, include=FALSE}

butter_hyper_PL_est_depth <- discountnonlinearest_PL_nothreshold_depth(df = butter_hyper_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[1]]
butter_super_PL_est_depth <- discountnonlinearest_PL_nothreshold_depth(df = butter_super_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[1]]

cereals_hyper_PL_est_depth <- discountnonlinearest_PL_nothreshold_depth(df = cereals_hyper_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[1]]
cereals_super_PL_est_depth <- discountnonlinearest_PL_nothreshold_depth(df = cereals_super_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[1]]

cream_hyper_PL_est_depth <- discountnonlinearest_PL_nothreshold_depth(df = cream_hyper_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[1]]
cream_super_PL_est_depth <- discountnonlinearest_PL_nothreshold_depth(df = cream_super_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[1]]

lactosefree_hyper_PL_est_depth <- discountnonlinearest_PL_nothreshold_depth(df = lactosefree_hyper_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[1]]
lactosefree_super_PL_est_depth <- discountnonlinearest_PL_nothreshold_depth(df = lactosefree_super_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[1]]


butter_hyper_PL_est_depth_plot <- discountnonlinearest_PL_nothreshold_depth(df = butter_hyper_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[2]]
butter_super_PL_est_depth_plot <- discountnonlinearest_PL_nothreshold_depth(df = butter_super_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[2]]

cereals_hyper_PL_est_depth_plot <- discountnonlinearest_PL_nothreshold_depth(df = cereals_hyper_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[2]]
cereals_super_PL_est_depth_plot <- discountnonlinearest_PL_nothreshold_depth(df = cereals_super_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[2]]

cream_hyper_PL_est_depth_plot <- discountnonlinearest_PL_nothreshold_depth(df = cream_hyper_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[2]]
cream_super_PL_est_depth_plot <- discountnonlinearest_PL_nothreshold_depth(df = cream_super_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[2]]


lactosefree_hyper_PL_est_depth_plot <- discountnonlinearest_PL_nothreshold_depth(df = lactosefree_hyper_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[2]]
lactosefree_super_PL_est_depth_plot <- discountnonlinearest_PL_nothreshold_depth(df = lactosefree_super_PL,alpha_l_price = 0,alpha_l_nondepth=0)[[2]]
Combined_result_depth_est <- rbind(
                          butter_hyper_PL_est_depth,butter_super_PL_est_depth,
                          cereals_hyper_PL_est_depth,cereals_super_PL_est_depth,
                          cream_hyper_PL_est_depth,cream_super_PL_est_depth,
                          lactosefree_hyper_PL_est_depth,lactosefree_super_PL_est_depth)


Combined_result_depth_plot <- rbind(
                          butter_hyper_PL_est_depth_plot,butter_super_PL_est_depth_plot,
                          cereals_hyper_PL_est_depth_plot,cereals_super_PL_est_depth_plot,
                          cream_hyper_PL_est_depth_plot,cream_super_PL_est_depth_plot,
                          lactosefree_hyper_PL_est_depth_plot,lactosefree_super_PL_est_depth_plot)
Combined_result_depth_plot$dlogprice_values <- as.numeric(Combined_result_depth_plot$dlogprice_values)
Combined_result_depth_plot$NLPE_values_pricebefore <- as.numeric(Combined_result_depth_plot$NLPE_values_pricebefore)
Combined_result_depth_plot$NLPE_values_depth <- as.numeric(Combined_result_depth_plot$NLPE_values_depth)
Combined_result_depth_plot$category <- as.factor(Combined_result_depth_plot$category)
Combined_result_depth_plot$format <- as.factor(Combined_result_depth_plot$format)

```


#Estimate Nonlinear Model WITH LEVEL
```{r eval=FALSE, include=FALSE}

butter_hyper_PL_est_discount <- discountnonlinearest_PL_nothreshold(df = butter_hyper_PL,alpha_l_price = 0,alpha_l_discount=0)[[1]]
butter_super_PL_est_discount <- discountnonlinearest_PL_nothreshold(df = butter_super_PL,alpha_l_price = 0,alpha_l_discount=0)[[1]]

cereals_hyper_PL_est_discount <- discountnonlinearest_PL_nothreshold(df = cereals_hyper_PL,alpha_l_price = 0,alpha_l_discount=0)[[1]]
cereals_super_PL_est_discount <- discountnonlinearest_PL_nothreshold(df = cereals_super_PL,alpha_l_price = 0,alpha_l_discount=0)[[1]]

cream_hyper_PL_est_discount <- discountnonlinearest_PL_nothreshold(df = cream_hyper_PL,alpha_l_price = 0,alpha_l_discount=0)[[1]]
cream_super_PL_est_discount <- discountnonlinearest_PL_nothreshold(df = cream_super_PL,alpha_l_price = 0,alpha_l_discount=0)[[1]]

lactosefree_hyper_PL_est_discount <- discountnonlinearest_PL_nothreshold(df = lactosefree_hyper_PL,alpha_l_price = 0,alpha_l_discount=0)[[1]]
lactosefree_super_PL_est_discount <- discountnonlinearest_PL_nothreshold(df = lactosefree_super_PL,alpha_l_price = 0,alpha_l_discount=0)[[1]]


butter_hyper_PL_est_discount_plot <- discountnonlinearest_PL_nothreshold(df = butter_hyper_PL,alpha_l_price = 0,alpha_l_discount=0)[[2]]
butter_super_PL_est_discount_plot <- discountnonlinearest_PL_nothreshold(df = butter_super_PL,alpha_l_price = 0,alpha_l_discount=0)[[2]]

cereals_hyper_PL_est_discount_plot <- discountnonlinearest_PL_nothreshold(df = cereals_hyper_PL,alpha_l_price = 0,alpha_l_discount=0)[[2]]
cereals_super_PL_est_discount_plot <- discountnonlinearest_PL_nothreshold(df = cereals_super_PL,alpha_l_price = 0,alpha_l_discount=0)[[2]]

cream_hyper_PL_est_discount_plot <- discountnonlinearest_PL_nothreshold(df = cream_hyper_PL,alpha_l_price = 0,alpha_l_discount=0)[[2]]
cream_super_PL_est_discount_plot <- discountnonlinearest_PL_nothreshold(df = cream_super_PL,alpha_l_price = 0,alpha_l_discount=0)[[2]]


lactosefree_hyper_PL_est_discount_plot <- discountnonlinearest_PL_nothreshold(df = lactosefree_hyper_PL,alpha_l_price = 0,alpha_l_discount=0)[[2]]
lactosefree_super_PL_est_discount_plot <- discountnonlinearest_PL_nothreshold(df = lactosefree_super_PL,alpha_l_price = 0,alpha_l_discount=0)[[2]]
Combined_result_discount_est <- rbind(
                          butter_hyper_PL_est_discount,butter_super_PL_est_discount,
                          cereals_hyper_PL_est_discount,cereals_super_PL_est_discount,
                          cream_hyper_PL_est_discount,cream_super_PL_est_discount,
                          lactosefree_hyper_PL_est_discount,lactosefree_super_PL_est_discount)


Combined_result_discount_plot <- rbind(
                          butter_hyper_PL_est_discount_plot,butter_super_PL_est_discount_plot,
                          cereals_hyper_PL_est_discount_plot,cereals_super_PL_est_discount_plot,
                          cream_hyper_PL_est_discount_plot,cream_super_PL_est_discount_plot,
                          lactosefree_hyper_PL_est_discount_plot,lactosefree_super_PL_est_discount_plot)
Combined_result_discount_plot$dlogprice_values <- as.numeric(Combined_result_discount_plot$dlogprice_values)
Combined_result_discount_plot$NLPE_values_pricebefore <- as.numeric(Combined_result_discount_plot$NLPE_values_pricebefore)
Combined_result_discount_plot$NLPE_values_discount <- as.numeric(Combined_result_discount_plot$NLPE_values_discount)
Combined_result_discount_plot$category <- as.factor(Combined_result_discount_plot$category)
Combined_result_discount_plot$format <- as.factor(Combined_result_discount_plot$format)

```

```{r plotting eval=FALSE, include=FALSE}
ggplot(Combined_result_discount_plot, aes(x = dlogprice_values, y = NLPE_values_pricebefore, color = category, linetype = format)) +
  geom_line() +
  labs(title = "Price BEFORE Elasticity",
       x = "dlogpricebefore",
       y = "NL_Pricebefore")

ggplot(Combined_result_discount_plot, aes(x = dlogprice_values, y = NLPE_values_discount, color = category, linetype = format)) +
  geom_line() +
  labs(title = "Effects of discounts across store format and category",
       x = "change of discount",
       y = "change of sales")
```

```{r gen lm indicator}
lm_indicator_butter_hyper_PL <- lm(dlogtotalvolume ~ dlogavgpricebefore_gain + dlogavgpricebefore_loss + dlognondepth_gain + dlognondepth_loss + dlogavgcompfinalprice + log(totalvolume1) + log(avgpricebefore1) + + log(nondepth1) + holiday,data=butter_hyper_PL)
lm_indicator_butter_super_PL <- lm(dlogtotalvolume ~ dlogavgpricebefore_gain + dlogavgpricebefore_loss + dlognondepth_gain + dlognondepth_loss + dlogavgcompfinalprice + log(totalvolume1) + log(avgpricebefore1) + + log(nondepth1) + holiday,data=butter_super_PL)
```

